package com.musinsa.subject.config

object CacheName {

    const val LOWEST_PRICE_BY_CATEGORY = "LOWEST_PRICE_BY_CATEGORY"
    const val LOWEST_TOTAL_PRICE_BRAND_WITH_CATEGORY_DETAILS = "LOWEST_TOTAL_PRICE_BRAND_WITH_CATEGORY_DETAILS"
    const val MIN_MAX_PRICE_BRANDS_BY_CATEGORY_NAME = "MIN_MAX_PRICE_BRANDS_BY_CATEGORY_NAME"

}
